'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user_cloud
    Public Property id As Integer
    Public Property user_code As String
    Public Property user_name As String
    Public Property user_pass As String
    Public Property user_mobile As String
    Public Property user_email As String
    Public Property pan_no As String
    Public Property dealer As String
    Public Property isactive As String
    Public Property EXPORT_TYPE As String
    Public Property MODIFIED_DATE As String
    Public Property MODIFIED_USER As String
    Public Property MULTI_LOC As String

End Class
