'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="D001DB21")>  _
Partial Public Class YourDataContextDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property dise_aprvls() As System.Data.Linq.Table(Of dise_aprvl)
		Get
			Return Me.GetTable(Of dise_aprvl)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.dise_aprvl")>  _
Partial Public Class dise_aprvl
	
	Private _Mob As String
	
	Private _Pan_No As String
	
	Private _Cust_Name As String
	
	Private _Modl_Var As String
	
	Private _Veh_Clr As String
	
	Private _Delv_Date As System.Nullable(Of Date)
	
	Private _Loan As String
	
	Private _MGA_Amt As System.Nullable(Of Decimal)
	
	Private _Insurance As String
	
	Private _RTO_Chrg As String
	
	Private _EW_CCP As String
	
	Private _Loyalty_Card As String
	
	Private _Car_Exch As String
	
	Private _FastTeg As String
	
	Private _SRM As String
	
	Private _RM As String
	
	Private _Consumer As System.Nullable(Of Decimal)
	
	Private _Corporate As System.Nullable(Of Decimal)
	
	Private _Exch As System.Nullable(Of Decimal)
	
	Private _Aprvl_Offer As System.Nullable(Of Decimal)
	
	Private _Dise_Amt As System.Nullable(Of Decimal)
	
	Private _Aprvl_By As String
	
	Private _Status As String
	
	Private _Remark As String
	
	Private _Curr_Date As System.Nullable(Of Date)
	
	Private _location As String
	
	Private _Approved_amt As System.Nullable(Of Decimal)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Mob", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property Mob() As String
		Get
			Return Me._Mob
		End Get
		Set
			If (String.Equals(Me._Mob, value) = false) Then
				Me._Mob = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Pan_No", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Pan_No() As String
		Get
			Return Me._Pan_No
		End Get
		Set
			If (String.Equals(Me._Pan_No, value) = false) Then
				Me._Pan_No = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cust_Name", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Cust_Name() As String
		Get
			Return Me._Cust_Name
		End Get
		Set
			If (String.Equals(Me._Cust_Name, value) = false) Then
				Me._Cust_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Modl_Var", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Modl_Var() As String
		Get
			Return Me._Modl_Var
		End Get
		Set
			If (String.Equals(Me._Modl_Var, value) = false) Then
				Me._Modl_Var = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Veh_Clr", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Veh_Clr() As String
		Get
			Return Me._Veh_Clr
		End Get
		Set
			If (String.Equals(Me._Veh_Clr, value) = false) Then
				Me._Veh_Clr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Delv_Date", DbType:="Date")>  _
	Public Property Delv_Date() As System.Nullable(Of Date)
		Get
			Return Me._Delv_Date
		End Get
		Set
			If (Me._Delv_Date.Equals(value) = false) Then
				Me._Delv_Date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loan", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Loan() As String
		Get
			Return Me._Loan
		End Get
		Set
			If (String.Equals(Me._Loan, value) = false) Then
				Me._Loan = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MGA_Amt", DbType:="Money")>  _
	Public Property MGA_Amt() As System.Nullable(Of Decimal)
		Get
			Return Me._MGA_Amt
		End Get
		Set
			If (Me._MGA_Amt.Equals(value) = false) Then
				Me._MGA_Amt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Insurance", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property Insurance() As String
		Get
			Return Me._Insurance
		End Get
		Set
			If (String.Equals(Me._Insurance, value) = false) Then
				Me._Insurance = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RTO_Chrg", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property RTO_Chrg() As String
		Get
			Return Me._RTO_Chrg
		End Get
		Set
			If (String.Equals(Me._RTO_Chrg, value) = false) Then
				Me._RTO_Chrg = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EW_CCP", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property EW_CCP() As String
		Get
			Return Me._EW_CCP
		End Get
		Set
			If (String.Equals(Me._EW_CCP, value) = false) Then
				Me._EW_CCP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Loyalty_Card", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Loyalty_Card() As String
		Get
			Return Me._Loyalty_Card
		End Get
		Set
			If (String.Equals(Me._Loyalty_Card, value) = false) Then
				Me._Loyalty_Card = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Car_Exch", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Car_Exch() As String
		Get
			Return Me._Car_Exch
		End Get
		Set
			If (String.Equals(Me._Car_Exch, value) = false) Then
				Me._Car_Exch = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FastTeg", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property FastTeg() As String
		Get
			Return Me._FastTeg
		End Get
		Set
			If (String.Equals(Me._FastTeg, value) = false) Then
				Me._FastTeg = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SRM", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property SRM() As String
		Get
			Return Me._SRM
		End Get
		Set
			If (String.Equals(Me._SRM, value) = false) Then
				Me._SRM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RM", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property RM() As String
		Get
			Return Me._RM
		End Get
		Set
			If (String.Equals(Me._RM, value) = false) Then
				Me._RM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Consumer", DbType:="Money")>  _
	Public Property Consumer() As System.Nullable(Of Decimal)
		Get
			Return Me._Consumer
		End Get
		Set
			If (Me._Consumer.Equals(value) = false) Then
				Me._Consumer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Corporate", DbType:="Money")>  _
	Public Property Corporate() As System.Nullable(Of Decimal)
		Get
			Return Me._Corporate
		End Get
		Set
			If (Me._Corporate.Equals(value) = false) Then
				Me._Corporate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Exch", DbType:="Money")>  _
	Public Property Exch() As System.Nullable(Of Decimal)
		Get
			Return Me._Exch
		End Get
		Set
			If (Me._Exch.Equals(value) = false) Then
				Me._Exch = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Aprvl_Offer", DbType:="Money")>  _
	Public Property Aprvl_Offer() As System.Nullable(Of Decimal)
		Get
			Return Me._Aprvl_Offer
		End Get
		Set
			If (Me._Aprvl_Offer.Equals(value) = false) Then
				Me._Aprvl_Offer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Dise_Amt", DbType:="Money")>  _
	Public Property Dise_Amt() As System.Nullable(Of Decimal)
		Get
			Return Me._Dise_Amt
		End Get
		Set
			If (Me._Dise_Amt.Equals(value) = false) Then
				Me._Dise_Amt = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Aprvl_By", DbType:="VarChar(20)")>  _
	Public Property Aprvl_By() As String
		Get
			Return Me._Aprvl_By
		End Get
		Set
			If (String.Equals(Me._Aprvl_By, value) = false) Then
				Me._Aprvl_By = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(10)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me._Status = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Remark", DbType:="VarChar(100)")>  _
	Public Property Remark() As String
		Get
			Return Me._Remark
		End Get
		Set
			If (String.Equals(Me._Remark, value) = false) Then
				Me._Remark = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Curr_Date", DbType:="Date")>  _
	Public Property Curr_Date() As System.Nullable(Of Date)
		Get
			Return Me._Curr_Date
		End Get
		Set
			If (Me._Curr_Date.Equals(value) = false) Then
				Me._Curr_Date = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_location", DbType:="VarChar(50)")>  _
	Public Property location() As String
		Get
			Return Me._location
		End Get
		Set
			If (String.Equals(Me._location, value) = false) Then
				Me._location = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Approved_amt", DbType:="Money")>  _
	Public Property Approved_amt() As System.Nullable(Of Decimal)
		Get
			Return Me._Approved_amt
		End Get
		Set
			If (Me._Approved_amt.Equals(value) = false) Then
				Me._Approved_amt = value
			End If
		End Set
	End Property
End Class
