<?xml version="1.0" encoding="utf-8"?><Database Name="D001DB21" Class="YourDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.dise_aprvl" Member="dise_aprvls">
    <Type Name="dise_aprvl">
      <Column Name="Mob" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Pan_No" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cust_Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Modl_Var" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Veh_Clr" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Delv_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Loan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MGA_Amt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Insurance" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RTO_Chrg" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EW_CCP" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Loyalty_Card" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Car_Exch" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FastTeg" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SRM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Consumer" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Corporate" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Exch" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Aprvl_Offer" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Dise_Amt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Aprvl_By" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Curr_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Approved_amt" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>